apiVersion: v1
kind: Service
metadata:
  name: eureka
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: LoadBalancer